name: Build and deploy Python app to Azure Web App

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies into package
        run: |
          python -m pip install --upgrade pip
          pip install --target=./python_packages -r requirements.txt

      - name: Zip artifact for deployment
        shell: powershell
        run: |
          Compress-Archive -Path @("app.py", "web.config", "requirements.txt", ".skipPythonDeployment", "static", "templates", "python_packages") -DestinationPath release.zip -Force

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ED46772FAB9E4D81AD3D7022657B2DA9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_557C41EAC41246E5820E1C56F0C126F4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_278F47A7989D4A489DFBBB793DDDCB78 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-web-medina-unl'
          slot-name: 'Production'
          package: release.zip
