name: Build and deploy .NET app to Azure Web App

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and publish
        run: dotnet publish -c Release -o ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ED46772FAB9E4D81AD3D7022657B2DA9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_557C41EAC41246E5820E1C56F0C126F4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_278F47A7989D4A489DFBBB793DDDCB78 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-web-medina-unl'
          slot-name: 'Production'
          package: ./publish
